### ISSUE TITLE
Quicken for Mac sqlite schema has changed - any plans to update these queries?

### ISSUE THREAD

**Issue by 42Network** [HarryDolan/qquery#1]
Quicken for Mac sqlite schema has changed - any plans to update these queries? I am using Quicken Premier 6.3.3

Also, what about a Python3 version?

I may make an attempt at these enhancements myself. I am still able to open my Quicken db with a SQLite utility and browse the tables.

For example, these queries still work:
```
select z_pk, zname, ztypename from zaccount;
select z_pk, zname, zuserdescription from ztag;
select count(*) from ZTRANSACTION;
```

Thanks

**Comment by HarryDolan** [comment]
Yeah, I realized that a while ago, but I haven’t used the module for some time.  Maybe now I will.

Harry

**Comment by 42Network** [comment]
I got it working on my system here. I just sent  you a PR for the 3 line
fix. I am a GitHub newbie, so let me know if I did something wrong with the
PR.

Nathan

**Comment by HarryDolan** [comment]
Thanks for the code, Nathan.  I accepted your pull request.

I also made a bunch of changes so that it works with python3 (long overdue).  I have them on my local system, but I too am a GitHub newbie and it will take a while to merge it in to GitHub.  I hope you’re not waiting for it.

Harry

**Comment by 42Network** [comment]
No rush. Works fine in Python 2 for me for now.

I think the sequence is git commit and git push. At least that's what I did after making a clone of your git. Then I used gh to create a PR.

PS: Have you ever tried *writing* to the Quicken DB via Python?

**Comment by HarryDolan** [comment]
I got it all onto GitHub.  And, no, I never tried writing to the Quicken DB.  I don’t dare! :-)

Harry
